#!/bin/bash

set -eu -o pipefail

basedir=$(dirname "$(readlink -f "$0")")

# This is missing profiles/repo_name since include that file would caused
# duplicate repo names

mkdir -p "$basedir"/distfiles/

cd $basedir

(find . -mindepth 3 -maxdepth 3 -name "*.ebuild" | xargs dirname \
  | sort | uniq | xargs find && echo metadata/layout.conf) \
  | cpio -o -H ustar --force-local \
  -O ./distfiles/cflowe-local.tar \
  && bzip2 -f ./distfiles/cflowe-local.tar
