#!/bin/bash

set -eu -o pipefail

basedir=$(dirname "$(readlink -f "$0")")

# This is missing profiles/repo_name since include that file would caused
# duplicate repo names

mkdir -p "$basedir"/distfiles/

(find "$basedir" -maxdepth 3 -name "*.ebuild" | xargs dirname \
  | sort | uniq | xargs find && echo metadata/layout.conf) \
  | cpio -o -H ustar --force-local \
  -O "$basedir"/distfiles/cflowe-local.tar \
  && bzip2 -f "$basedir"/distfiles/cflowe-local.tar 
